### ISSUE TITLE
Image squeezed into square size on iOS

### ISSUE THREAD

**Issue by aghoneim92** [TEAM-PREAT/peekaboo#44]
When picking a non-square image on iOS, it is squeezed/stretched into a square

My code:
```kotlin
val picture = remember { mutableStateOf<ByteArray?>(null) }
val imagePicker =
        rememberImagePickerLauncher(
            selectionMode = SelectionMode.Single,
            scope = scope,
            onResult = { byteArrays ->
              byteArrays.firstOrNull()?.let { picture.value = it }
            },
        )
val pictureValue = picture.value
if (pictureValue != null) {
      Image(
          bitmap = pictureValue.toImageBitmap(),
          contentDescription = "Profile Picture",
          modifier = Modifier.fillMaxSize(),
          contentScale = ContentScale.Fit,
      )
}
```
## Original image:

![Cat03](https://github.com/TEAM-PREAT/peekaboo/assets/23440101/42c19c6f-58e1-4c6d-82a9-cf078f6115f5)

## Rendered Image:
<img width="383" alt="Screenshot 2024-01-13 at 1 06 19 AM" src="https://github.com/TEAM-PREAT/peekaboo/assets/23440101/d9891df1-afc8-4ac5-bb14-3c09548acba1">

**Comment by onseok** [comment]
This issue has been resolved in [1cada09](https://github.com/TEAM-PREAT/peekaboo/pull/49/commits/10969d5a37b0f771505119e141f38d02012cecaa). 

Thanks for pointing it out! @aghoneim92 😊

**Comment by onseok** [comment]
> @onseok Any idea when can a new update be released with this change. We want to use this in production app.

Hi @LaatonWalaBhoot, the new version `0.4.2`, which includes this change has just been released. 
Thank you 😊

**Comment by LaatonWalaBhoot** [comment]
Thanks so much for a fast response
